#!/usr/bin/env bash
# Debug-only launcher for the single failing sample discussed in the logs.
# Default target:
# - component_id = 1
# - start = 4
# - limit = 1
#
# This is intended to isolate:
#   Example 5 | line=18 | GT=option3
#
# You can still append extra args to override any default.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Keep the same model/API config behavior as the main launcher.
# The underlying runner now enables LLM debug by default.

export AGENTDEBUG_MODEL_NAME="${AGENTDEBUG_MODEL_NAME:-intern-s1}"
export AGENTDEBUG_MODEL_AGENT="${AGENTDEBUG_MODEL_AGENT:-${AGENTDEBUG_MODEL_NAME}}"
export AGENTDEBUG_MODEL_MCP="${AGENTDEBUG_MODEL_MCP:-${AGENTDEBUG_MODEL_NAME}}"
export MODEL_PLANNER="${MODEL_PLANNER:-intern-s1-pro}"
export MODEL_CLAIM="${MODEL_CLAIM:-intern-s1}"
export AGENTDEBUG_THINKING_MODE="${AGENTDEBUG_THINKING_MODE:-false}"
export BRIGHT_DATA_API_KEY="${BRIGHT_DATA_API_KEY:-}"
export BRIGHT_DATA_ZONE="${BRIGHT_DATA_ZONE:-}"
export AGDEBUGGER_CLAIM_USE_WEBSEARCH="${AGDEBUGGER_CLAIM_USE_WEBSEARCH:-1}"
export AGDEBUGGER_CLAIM_SEARCH_MAX_SEARCHES="${AGDEBUGGER_CLAIM_SEARCH_MAX_SEARCHES:-2}"
export AGDEBUGGER_CLAIM_SEARCH_NUM_RESULTS="${AGDEBUGGER_CLAIM_SEARCH_NUM_RESULTS:-3}"
export AGDEBUGGER_CLAIM_SEARCH_FETCH_TOP_N="${AGDEBUGGER_CLAIM_SEARCH_FETCH_TOP_N:-0}"
export AGDEBUGGER_CLAIM_SEARCH_MAX_OUTPUT_WORDS="${AGDEBUGGER_CLAIM_SEARCH_MAX_OUTPUT_WORDS:-1200}"
export AGDEBUGGER_ANALYSIS_PER_CLAIM_TIMEOUT_SEC="${AGDEBUGGER_ANALYSIS_PER_CLAIM_TIMEOUT_SEC:-90}"
export AGDEBUGGER_CONCEPT_EXTRACTION_MODE="${AGDEBUGGER_CONCEPT_EXTRACTION_MODE:-heuristic}"
export AGDEBUGGER_CONCEPT_MAX_CLAIMS_PER_TURN="${AGDEBUGGER_CONCEPT_MAX_CLAIMS_PER_TURN:-4}"
export AGDEBUGGER_CONCEPT_MAX_TOTAL_CLAIMS="${AGDEBUGGER_CONCEPT_MAX_TOTAL_CLAIMS:-6}"
export AGDEBUGGER_STRICT_CONCEPT_REPAIR_ONLY="${AGDEBUGGER_STRICT_CONCEPT_REPAIR_ONLY:-1}"
export AGDEBUGGER_MAX_CONCEPT_REPAIR_ATTEMPTS="${AGDEBUGGER_MAX_CONCEPT_REPAIR_ATTEMPTS:-3}"

DEFAULT_COMPONENT_ID="${DEFAULT_COMPONENT_ID:-1}"
DEFAULT_START="${DEFAULT_START:-4}"
DEFAULT_LIMIT="${DEFAULT_LIMIT:-1}"

exec bash "${SCRIPT_DIR}/run_with_models.sh" \
    --component-id "${DEFAULT_COMPONENT_ID}" \
    --start "${DEFAULT_START}" \
    --limit "${DEFAULT_LIMIT}" \
    "$@"
